version: '3'
services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /home/aqua/timescale_data:/var/lib/postgresql/data
